# Generated by Django 5.0.3 on 2025-01-28 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('turf_name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='media/')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('available_slots', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('time_slot', models.CharField(default='default_value', max_length=50)),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
                ('turf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='myapp.turf')),
            ],
        ),
    ]
