# Generated by Django 5.0.3 on 2025-01-30 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='gmail',
            new_name='email',
        ),
    ]
